### ISSUE TITLE
Voided Docs pair keep unvoid

### ISSUE THREAD

**Issue by arqlz** [jraede/medici#2]
When voiding a transaction the void pair keeps unvoid, so you could not filter only unvoids.
EXAMPLE:

var Libro = new medici.book('Libro');
Libro.entry("test").debit("Activos:Banco", 5000).credit("Gastos:Proyecto", 5000).commit()
    .then( function (journal) {
        // ill ignore the returned journal
        Libro.ledger("Activos").then( function(docs) {
            // Now ill void the first item
            Libro.void( docs.results[0]._journal, "Error" ).then( function () {
                // ill check the results
                Libro.ledger("Activos").then( function(docs) {
                    console.log(docs);
                });            
            });
        });
});

**Comment by jraede** [comment]
I'm not sure I understand the issue - can you clarify?

**Comment by arqlz** [comment]
If an entry (erroneous one) is voided, a copy is made with contrary values. And The first one property voided is turn to true. But the new negative one property voided keep true. So if you use ledger youll get the new unvoid transacción but no The last voided one. I think both should be tagget as voided = true

**Comment by jraede** [comment]
So do you need a flag to designate if a transaction was created in order to neutralize a voided transaction? Can't you just look to see if a transaction has an `_original_journal` property, which would mean that it was created in order to void a transaction in another journal entry?

**Comment by arqlz** [comment]
Not what i was thinking about, but thanks, it works for me

**Comment by muenzel** [comment]
When I void an journal entry then the transactions are marked as voided but the journal entry is not.

Both the transaction as well as the journal entry have the 'approved' and 'voided' flags, but it seems that the voided flag from the journal is not used at all (or am I missing something)

**Comment by koresar** [comment]
Thank you for the contribution. I'll take a look on Monday. Do you have
time to wait few days?
